services:
  
  postgres:
    image: postgres:latest
    container_name: health_system_postgres
    environment:
      POSTGRES_DB: health_system_database
      POSTGRES_USER: health_system_user
      POSTGRES_PASSWORD: HealthSystem1
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - health_system_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: health_system_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: superadmin@hsb.co.ke
      PGADMIN_DEFAULT_PASSWORD: HealthSystem#123
    ports:
      - "8083:80"
    networks:
      - health_system_network

  adminer:
    image: adminer:latest
    container_name: health_system_adminer
    ports:
      - "8084:8080"
    networks:
      - health_system_network

volumes:
  postgres_data:

networks:
  health_system_network: